Project initial functionalities up to cart system
Azan30/Dinner-dash pull request #2
Opened 2020-10-14 06:56 UTC by Azan30

Kindly please verify my branch code so that i can merge it with my master branch

2020-10-14 13:40 UTC, ziaulrehman40 commented
Branch name, files, PR size, commit messages, PR description, and PR title, everything is wrong here.

2020-10-14 15:15 UTC, farooqahmad075 requested changes

2020-10-14 15:15 UTC, farooqahmad075 commented on Gemfile
> +  gem 'web-console', '>= 3.3.0'
No need to remove and re-add the same line.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/assets/javascripts/application.js
> +//= require bootstrap-sprockets
Please Re-consider these requires.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/assets/stylesheets/application.scss
> +}
```suggestion
.resize {
  width: 100%;
}
```

2020-10-14 15:15 UTC, farooqahmad075 commented on app/assets/stylesheets/application.scss
> +}
```suggestion
.nav-link {
  padding-right: .5rem !important;
  padding-left: .5rem !important;
}

.spacing {
  padding-left: 100px;
}
```

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/application_controller.rb
> +    flash[:alert] = "You are not authorized to perform this action."
Please use single quote.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/cart_controller.rb
> +  end
* introduce a method in cart model to add item into it instead of controller.
* Remove testing
* Simply the code

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/cart_controller.rb
> +  end
Same here.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/cart_controller.rb
> +  end
Remove this useless code.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/categories_controller.rb
> +    redirect_to categories_path
Add a condition to check either it is destroyed or not?

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/categories_controller.rb
> +  end
Move it to category model.
Use nested route for item under category.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/users/confirmations_controller.rb
> +# frozen_string_literal: true
Please remove this file.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/users/omniauth_callbacks_controller.rb
> +# frozen_string_literal: true
Remove this as well

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/users/passwords_controller.rb
> +# frozen_string_literal: true
remove this as well.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/users/registrations_controller.rb
> +# frozen_string_literal: true
same

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/users/sessions_controller.rb
> +# frozen_string_literal: true
same

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/users/unlocks_controller.rb
> +# frozen_string_literal: true
same

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/welcome_controller.rb
> +    if User.find(current_user.id).cart.nil?
Please use eager loading here. means includes items in categories.

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/welcome_controller.rb
> +    if User.find(current_user.id).cart.nil?
current_user.cart only

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/welcome_controller.rb
> +      @cart = Cart.create({user: current_user })
please use current_user.cart.create()

2020-10-14 15:15 UTC, farooqahmad075 commented on app/controllers/welcome_controller.rb
> +      @cart = User.find(current_user.id).cart
current_user.cart

2020-10-14 15:15 UTC, farooqahmad075 commented on app/helpers/items_helper.rb
> +      if i.title == item.title
```suggestion
    current_user.cart.line_items.each do |cart_item|
      if cart_item.item.title == item.title
```

2020-10-14 15:15 UTC, farooqahmad075 commented on app/helpers/orders_helper.rb
> +    all_items = all_items.join(', ')
```suggestion
    all_items = items.pluck(:title).join(', ')
```

2020-10-14 15:15 UTC, farooqahmad075 commented on app/models/cart.rb
> +  has_many :line_items, dependent: :destroy
cart_items

2020-10-14 15:15 UTC, farooqahmad075 commented on app/models/item.rb
> +  has_many :line_items
cart_items

2020-10-14 15:15 UTC, farooqahmad075 commented on app/models/order.rb
> +  validates :status, presence: true
add empty line here.

2020-10-14 18:11 UTC, Azan30 commented on app/controllers/welcome_controller.rb
> +      @cart = Cart.create({user: current_user })
this line of code is not working

2020-10-15 09:32 UTC, farooqahmad075 requested changes

2020-10-15 09:32 UTC, farooqahmad075 commented on app/models/user.rb
> +  end
instead of `after_create` please use before_create and avoid the update_attribute call.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/policies/order_policy.rb
> +        user.orders
please use `user.Admin?`

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/cart/show.html.erb
> +    <% end -%>
align the indentation.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/cart/show.html.erb
> +      <% @cart.line_items.each do |line_item| %>
@cart.cart_item

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/cart/show.html.erb
> +          <td> 1 </td>
don't hard code the quantity.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/categories/category_items.html.erb
> +
I think now there is no need for this view.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/cart/add.js.erb
> +});
Use Unobtrusive JavaScript.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/cart/remove.js.erb
> +});
Use Unobtrusive JavaScript.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/categories/index.html.erb
> +    <% end -%>
Indentation issue.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/categories/index.html.erb
> +          <% if current_user.type == 'Admin'%>
please use current_user.Admin?

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/categories/index.html.erb
> +        <td><%= link_to 'Show Items', category_items_category_path(category) %></td>
please change this path

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/categories/show.html.erb
> +rahi controler sy or us ka data notice ma rakhwa kr view ko pass kr rahi %>
remove these lines.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/categories/_form.html.erb
> +<%= form_with model: @category, local: true do |form| %>
remove local: true

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/items/_form.html.erb
> +<%= form_with model: @item, local: true do |form| %>
same here.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/items/index.html.erb
> +    <% end -%>
Same here.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/items/index.html.erb
> +        <% if current_user.type == 'Admin'%>
same change of Admin?

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/items/index.html.erb
> +    <% end -%>
Move that code to a shared errors partial.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/items/index.html.erb
> +          <% if current_user.type == 'Admin'%>
same here.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/items/index.html.erb
> +<% if current_user.type == 'Admin'%>
same here.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/items/new.html.erb
> +<h1>New Article</h1>
New Item

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/orders/_form.html.erb
> +<%= form_with model: @order, local: true do |form| %>
remove local

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/orders/_form.html.erb
> +  <% end %>
Move to errors shared partial.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/orders/edit.html.erb
> +  <% if @order.errors.any? %>
move to shared errors partial.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/orders/edit.html.erb
> +<%= form_with model: @order, local: true do |form| %>
move to _form partial.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/orders/edit.html.erb
> +    <% status = ['Pending', 'Canceled','Completed', 'In Progress'] %>
move it to a Constant and freeze that array.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/orders/index.html.erb
> +    <% end -%>
there is some issue in syntax.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/orders/index.html.erb
> +    <% status = ['All','Pending', 'Canceled','Completed', 'In Progress'] %>
same for these as well.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/orders/index.html.erb
> +          <td><%= titles(items)%></td>
pass order.item

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/confirmations/new.html.erb
> +<%= render "users/shared/links" %>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/mailer/confirmation_instructions.html.erb
> +<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/mailer/email_changed.html.erb
> +<% end %>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/mailer/password_change.html.erb
> +<p>We're contacting you to notify you that your password has been changed.</p>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/mailer/reset_password_instructions.html.erb
> +<p>Your password won't change until you access the link above and create a new one.</p>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/mailer/unlock_instructions.html.erb
> +<p><%= link_to 'Unlock my account', unlock_url(@resource, unlock_token: @token) %></p>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/passwords/edit.html.erb
> +<%= render "users/shared/links" %>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/passwords/new.html.erb
> +<h2>Forgot your password?</h2>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/registrations/edit.html.erb
> +<h2>Edit <%= resource_name.to_s.humanize %></h2>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/sessions/new.html.erb
> +<h2>Log in</h2>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/shared/_error_messages.html.erb
> +<% if resource.errors.any? %>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/shared/_links.html.erb
> +<%- if controller_name != 'sessions' %>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/users/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
remove this file.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/welcome/index.html.erb
> +
remove one extra line.

2020-10-15 09:32 UTC, farooqahmad075 commented on app/views/welcome/index.html.erb
> +                    <% end %>
change c,i into category, item.

2020-10-15 09:32 UTC, farooqahmad075 commented on bin/rails
> +  load File.expand_path('spring', __dir__)
revert this one.

2020-10-15 09:32 UTC, farooqahmad075 commented on bin/rake
> +  load File.expand_path('spring', __dir__)
revert this as well.

2020-10-15 09:32 UTC, farooqahmad075 commented on config/application.rb
> -# you've limited to :test, :development, or :production.
re-place these lines.

2020-10-15 09:32 UTC, farooqahmad075 commented on config/routes.rb
> +      get 'remove'
update the routes.

2020-10-15 09:32 UTC, farooqahmad075 commented on db/migrate/20201013194755_add_cart_to_line_item.rb
> +end
remove this mogration.

2020-10-15 09:32 UTC, farooqahmad075 commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2020_10_13_194755) do
please add the latest schema file with updated migrations.

2020-10-16 08:02 UTC, farooqahmad075 approved these changes
Now looks good to me. 👍

2020-10-16 08:14 UTC, merged